name: Main CI/CD Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout library code & submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Display Triggering Event
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             echo "Target branch: ${{ github.base_ref }}"
          fi

      - name: Build library from source
        run: |
          cmake . && make all
          
      - name: Testing library
        run: |
          ./Test

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
           echo "Please come back later!" # TODO: Doxygen integration
