name: Main CI/CD Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout library code & submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Display Triggering Event
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             echo "Target branch: ${{ github.base_ref }}"
          fi

      - name: Build library from source
        run: |
          cmake . && make all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

      - name: Upload config files
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-config
          path: benchmark/config.json

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/

      - name: Testing library - unit tests
        run: |
          chmod +x ./build/Test
          ./build/Test [unit]
    
      - name: Testing library - corner cases
        run: |
          chmod +x ./build/Test
          ./build/Test [corner] # TODO: -r compact? # TODO: -s for performance tests
      
      - name: Testing library - stress tests
        run: |
          chmod +x ./build/Test
          ./build/Test [stress]

  benchmark:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build/
      
      - name: Download benchmark config
        uses: actions/download-artifact@v4
        with:
          name: benchmark-config
          path: benchmark/

      - name: Debug - List active directories
        run: |
          ls -R ./

      - name: Benchmark
        run: |
          chmod +x ./build/Benchmark
          ./build/Benchmark --benchmark_format=json > ./benchmark/results.json

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
           echo "Please come back later!" # TODO: Doxygen integration
