name: Main CI/CD Workflow

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display Triggering Event
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             echo "Target branch: ${{ github.base_ref }}"
          fi

      - name: Build library from source
        run: |
          cmake -B third_party/catch2/build -S third_party/catch2 -DBUILD_TESTING=OFF
          cmake --build third_party/catch2/build --target install 
          cmake . && make StringLib
          make Test
          
          
      - name: Testing library
        run: |
          ./test/Test

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
           echo "Please come back later!" # TODO: Doxygen integration
